"""Application port — same contract satisfied by both Postgres and Redis adapters."""
from __future__ import annotations

from typing import Protocol, runtime_checkable

from src.domain.item import Item


@runtime_checkable
class ItemRepositoryPort(Protocol):
    async def get(self, item_id: str) -> Item | None: ...
    async def list(self, limit: int, offset: int) -> tuple[list[Item], int]: ...
    async def create(self, item: Item) -> Item: ...
    async def update(self, item: Item) -> Item | None: ...
    async def delete(self, item_id: str) -> bool: ...
    async def ping(self) -> bool: ...
    async def is_ready(self) -> bool: ...
