"""Application port for artifact persistence."""
from __future__ import annotations

from typing import Protocol, runtime_checkable

from src.domain.artifact import EmbeddingStatus, ResearchArtifact


@runtime_checkable
class ArtifactRepositoryPort(Protocol):
    async def get(self, artifact_id: str) -> ResearchArtifact | None: ...
    async def list(self, limit: int, offset: int) -> tuple[list[ResearchArtifact], int]: ...
    async def create(self, artifact: ResearchArtifact) -> ResearchArtifact: ...
    async def update(self, artifact: ResearchArtifact) -> ResearchArtifact | None: ...
    async def delete(self, artifact_id: str) -> bool: ...
    async def ping(self) -> bool: ...
    async def is_ready(self) -> bool: ...
