from typing import List, Optional, Protocol, Tuple

from domain.swap_item import SwapItem


class SwapItemRepository(Protocol):
    async def save(self, item: SwapItem) -> None: ...
    async def get(self, item_id: str) -> Optional[SwapItem]: ...
    async def list(self, limit: int = 20, offset: int = 0) -> Tuple[List[SwapItem], int]: ...
    async def delete(self, item_id: str) -> bool: ...
