from typing import List, Optional, Protocol

from domain.swap_item import SwapItem


class SwapItemRepository(Protocol):
    async def save(self, item: SwapItem) -> None: ...
    async def get(self, item_id: str) -> Optional[SwapItem]: ...
    async def list(self) -> List[SwapItem]: ...
    async def delete(self, item_id: str) -> bool: ...
