"""Application-specific port for event publishing."""
from __future__ import annotations

from typing import Protocol, runtime_checkable

from src.domain.order_event import OrderEvent


@runtime_checkable
class EventPublisherPort(Protocol):
    async def publish(self, event: OrderEvent) -> None: ...
    async def publish_batch(self, events: list[OrderEvent]) -> None: ...
    async def publish_keyed(self, key: str, event: OrderEvent) -> None: ...
    async def get_topic_metadata(self) -> dict: ...
    async def close(self) -> None: ...
