"""Application-specific port for session persistence."""
from __future__ import annotations

from typing import Protocol, runtime_checkable

from src.domain.session import Session


@runtime_checkable
class SessionRepositoryPort(Protocol):
    async def get(self, session_id: str) -> Session | None: ...
    async def list(self, limit: int, offset: int) -> tuple[list[Session], int]: ...
    async def create(self, session: Session) -> Session: ...
    async def update(self, session: Session) -> Session | None: ...
    async def delete(self, session_id: str) -> bool: ...
    async def extend_ttl(self, session_id: str, seconds: int) -> bool: ...
    async def get_stats(self) -> dict: ...
    async def ping(self) -> bool: ...
    async def is_ready(self) -> bool: ...
